document.addEventListener('DOMContentLoaded', function () {
  const filmList = document.getElementById('filmForm');

  filmList.addEventListener('submit', function (event) {
    // MENCEGAH RELOAD
    event.preventDefault();

    // MENGAMBIL DATA DARI FORM
    let mbti = document.getElementById('mbti').value;
    let umur = document.getElementById('age_rating').value;
    let mood = document.getElementById('mood').value;
    let genre = document.getElementById('genre').value.toLowerCase();

    // DATA BANK FILM
    const filmData = {
      intj: [
        {
          mood: 'excited',
          genre: 'aksi',
          title: 'Inception',
          img: 'https://media.themoviedb.org/t/p/w300_and_h450_bestv2/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg',
          age_rating: '13',
        },
        {
          mood: 'excited',
          genre: 'aksi',
          title: 'The Dark Knight',
          img: 'https://media.themoviedb.org/t/p/w600_and_h900_bestv2/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
          age_rating: '13',
        },
        {
          mood: 'excited',
          genre: 'aksi',
          title: 'John Wick',
          img: 'https://media.themoviedb.org/t/p/w600_and_h900_bestv2/TxbvYS8wsgYSpYZtQLZXnoVOIQ.jpg',
          age_rating: '17',
        },
        {
          mood: 'excited',
          genre: 'fiksi ilmiah',
          title: 'Interstellar',
          img: 'https://media.themoviedb.org/t/p/w600_and_h900_bestv2/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
          age_rating: '13',
        },
        {
          mood: 'excited',
          genre: 'fiksi ilmiah',
          title: 'Blade Runner 2049',
          img: 'https://media.themoviedb.org/t/p/w600_and_h900_bestv2/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg',
          age_rating: '17',
        },
        {
          mood: 'excited',
          genre: 'fiksi ilmiah',
          title: 'Arrival',
          img: 'https://media.themoviedb.org/t/p/w600_and_h900_bestv2/x2FJsf1ElAgr63Y3PNPtJrcmpoe.jpg',
          age_rating: '13',
        },
        {
          mood: 'calm',
          genre: 'drama',
          title: 'The Shawshank Redemption',
          img: 'https://media.themoviedb.org/t/p/w600_and_h900_bestv2/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg',
          age_rating: '15',
        },
        {
          mood: 'calm',
          genre: 'drama',
          title: 'The Godfather',
          img: 'https://media.themoviedb.org/t/p/w600_and_h900_bestv2/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
          age_rating: '17',
        },
        {
          mood: 'calm',
          genre: 'drama',
          title: '12 Angry Men',
          img: 'https://media.themoviedb.org/t/p/w600_and_h900_bestv2/ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg',
          age_rating: '13',
        },
        {
          mood: 'calm',
          genre: 'misteri',
          title: 'Sherlock Holmes',
          img: 'https://media.themoviedb.org/t/p/w600_and_h900_bestv2/thC0OuUvfGbOcoJ3aY5L4vlO6lA.jpg',
          age_rating: '13',
        },
        {
          mood: 'calm',
          genre: 'misteri',
          title: 'Zodiac',
          img: 'https://media.themoviedb.org/t/p/w600_and_h900_bestv2/6YmeO4pB7XTh8P8F960O1uA14JO.jpg',
          age_rating: '15',
        },
        {
          mood: 'calm',
          genre: 'misteri',
          title: 'The Girl with the Dragon Tattoo',
          img: 'https://media.themoviedb.org/t/p/w600_and_h900_bestv2/vbLedKc1BUF4FOH1GyHW62FulCc.jpg',
          age_rating: '17',
        },
        {
          mood: 'happy',
          genre: 'komedi',
          title: 'Monty Python and the Holy Grail',
          img: 'https://media.themoviedb.org/t/p/w600_and_h900_bestv2/hWx1ANiWEWWyzKPN0us35HCGnhQ.jpg',
          age_rating: '13',
        },
        {
          mood: 'happy',
          genre: 'komedi',
          title: 'The Big Lebowski',
          img: 'https://media.themoviedb.org/t/p/w600_and_h900_bestv2/9mprbw31MGdd66LR0AQKoDMoFRv.jpg',
          age_rating: '17',
        },
        {
          mood: 'happy',
          genre: 'komedi',
          title: 'Shaun of the Dead',
          img: 'https://media.themoviedb.org/t/p/w600_and_h900_bestv2/dgXPhzNJH8HFTBjXPB177yNx6RI.jpg',
          age_rating: '17',
        },
        {
          mood: 'happy',
          genre: 'animasi',
          title: 'Spirited Away',
          img: 'https://media.themoviedb.org/t/p/w600_and_h900_bestv2/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',
          age_rating: '10',
        },
        {
          mood: 'happy',
          genre: 'animasi',
          title: 'Wall-E',
          img: 'https://i.pinimg.com/736x/f2/5b/e0/f25be05af79802b72455b7b34cc80e6d.jpg',
          age_rating: '10',
        },
        {
          mood: 'happy',
          genre: 'animasi',
          title: 'Inside Out',
          img: 'https://i.pinimg.com/474x/6d/71/e7/6d71e72ccb7199f965f6b8106267a8e8.jpg',
          age_rating: '10',
        },
        {
          mood: 'sad',
          genre: 'drama',
          title: "Schindler's List",
          img: 'https://i.pinimg.com/474x/58/7a/2a/587a2a1dbb33437d4c48811e020c4ec8.jpg',
          age_rating: '15',
        },
        {
          mood: 'sad',
          genre: 'drama',
          title: 'The Pianist',
          img: 'https://media.themoviedb.org/t/p/w600_and_h900_bestv2/2hFvxCCWrTmCYwfy7yum0GKRi3Y.jpg',
          age_rating: '15',
        },
        {
          mood: 'sad',
          genre: 'drama',
          title: 'Manchester by the Sea',
          img: 'https://media.themoviedb.org/t/p/w600_and_h900_bestv2/o9VXYOuaJxCEKOxbA86xqtwmqYn.jpg',
          age_rating: '17',
        },
        {
          mood: 'sad',
          genre: 'romantis',
          title: 'The Notebook',
          img: 'https://media.themoviedb.org/t/p/w600_and_h900_bestv2/rNzQyW4f8B8cQeg7Dgj3n6eT5k9.jpg',
          age_rating: '13',
        },
        {
          mood: 'sad',
          genre: 'romantis',
          title: 'Eternal Sunshine of the Spotless Mind',
          img: 'https://media.themoviedb.org/t/p/w600_and_h900_bestv2/5MwkWH9tYHv3mV9OdYTMR5qreIz.jpg',
          age_rating: '17',
        },
      ],
      intp: [
        {
          mood: 'excited',
          genre: 'aksi',
          title: 'Inception',
          img: 'https://media.themoviedb.org/t/p/w600_and_h900_bestv2/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg',
          age_rating: '13',
        },
        {
          mood: 'excited',
          genre: 'aksi',
          title: 'The Matrix',
          img: 'https://media.themoviedb.org/t/p/w600_and_h900_bestv2/dXNAPwY7VrqMAo51EKhhCJfaGb5.jpg',
          age_rating: '17',
        },
        {
          mood: 'excited',
          genre: 'fiksi ilmiah',
          title: 'Interstellar',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
          age_rating: '13',
        },
        {
          mood: 'excited',
          genre: 'fiksi ilmiah',
          title: 'Arrival',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/x2FJsf1ElAgr63Y3PNPtJrcmpoe.jpg',
          age_rating: '13',
        },
        {
          mood: 'calm',
          genre: 'drama',
          title: 'A Beautiful Mind',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/rEIg5yJdNOt9fmX4P8gU9LeNoTQ.jpg',
          age_rating: '13',
        },
        {
          mood: 'calm',
          genre: 'drama',
          title: 'The Imitation Game',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/zSqJ1qFq8NXFfi7JeIYMlzyR0dx.jpg',
          age_rating: '13',
        },
        {
          mood: 'calm',
          genre: 'misteri',
          title: 'Zodiac',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/6YmeO4pB7XTh8P8F960O1uA14JO.jpg',
          age_rating: '15',
        },
        {
          mood: 'calm',
          genre: 'misteri',
          title: 'Memento',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/nWtySDlffTfwAa0rSfq61o33ZXV.jpg',
          age_rating: '17',
        },
        {
          mood: 'happy',
          genre: 'komedi',
          title: 'The Big Lebowski',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/9mprbw31MGdd66LR0AQKoDMoFRv.jpg',
          age_rating: '17',
        },
        {
          mood: 'happy',
          genre: 'komedi',
          title: 'Shaun of the Dead',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/dgXPhzNJH8HFTBjXPB177yNx6RI.jpg',
          age_rating: '17',
        },
        {
          mood: 'happy',
          genre: 'animasi',
          title: 'Spirited Away',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',
          age_rating: '10',
        },
        {
          mood: 'happy',
          genre: 'animasi',
          title: 'Wall-E',
          img: 'https://i.pinimg.com/736x/f2/5b/e0/f25be05af79802b72455b7b34cc80e6d.jpg',
          age_rating: '10',
        },
        {
          mood: 'sad',
          genre: 'drama',
          title: 'Manchester by the Sea',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/o9VXYOuaJxCEKOxbA86xqtwmqYn.jpg',
          age_rating: '17',
        },
        {
          mood: 'sad',
          genre: 'drama',
          title: 'Eternal Sunshine of the Spotless Mind',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/5MwkWH9tYHv3mV9OdYTMR5qreIz.jpg',
          age_rating: '17',
        },
        {
          mood: 'sad',
          genre: 'fiksi ilmiah',
          title: 'Moon',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/35IU0Mq0zFsN1mYwDGts5mKc77n.jpg',
          age_rating: '15',
        },
      ],
      entj: [
        {
          mood: 'excited',
          genre: 'aksi',
          title: 'Inception',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg',
          age_rating: '13',
        },
        {
          mood: 'excited',
          genre: 'aksi',
          title: 'The Dark Knight',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
          age_rating: '13',
        },
        {
          mood: 'excited',
          genre: 'fiksi ilmiah',
          title: 'Interstellar',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
          age_rating: '13',
        },
        {
          mood: 'excited',
          genre: 'fiksi ilmiah',
          title: 'Minority Report',
          img: 'https://media.themoviedb.org/t/p/w600_and_h900_bestv2/oUbANT6vjAFbHvhDQ3cxCZOzPK1.jpg',
          age_rating: '13',
        },
        {
          mood: 'calm',
          genre: 'drama',
          title: 'The Social Network',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/n0ybibhJtQ5icDqTp8eRytcIHJx.jpg',
          age_rating: '13',
        },
        {
          mood: 'calm',
          genre: 'drama',
          title: 'Moneyball',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/4yIQq1e6iOcaZ5rLDG3lZBP3j7a.jpg',
          age_rating: '13',
        },
        {
          mood: 'calm',
          genre: 'misteri',
          title: 'Zodiac',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/6YmeO4pB7XTh8P8F960O1uA14JO.jpg',
          age_rating: '15',
        },
        {
          mood: 'calm',
          genre: 'misteri',
          title: 'Sherlock Holmes',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/thC0OuUvfGbOcoJ3aY5L4vlO6lA.jpg',
          age_rating: '13',
        },
        {
          mood: 'happy',
          genre: 'komedi',
          title: 'The Wolf of Wall Street',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/kW9LmvYHAaS9iA0tHmZVq8hQYoq.jpg',
          age_rating: '17',
        },
        {
          mood: 'happy',
          genre: 'komedi',
          title: 'Thank You for Smoking',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/cJpeM7U36diFinieBWNLVi0FlQz.jpg',
          age_rating: '17',
        },
        {
          mood: 'happy',
          genre: 'animasi',
          title: 'The Incredibles',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/2LqaLgk4Z226KkgPJuiOQ58wvrm.jpg',
          age_rating: '10',
        },
        {
          mood: 'happy',
          genre: 'animasi',
          title: 'Ratatouille',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/t3vaWRPSf6WjDSamIkKDs1iQWna.jpg',
          age_rating: '10',
        },
        {
          mood: 'sad',
          genre: 'drama',
          title: "Schindler's List",
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg',
          age_rating: '15',
        },
        {
          mood: 'sad',
          genre: 'drama',
          title: 'The Pianist',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/2hFvxCCWrTmCYwfy7yum0GKRi3Y.jpg',
          age_rating: '15',
        },
        {
          mood: 'sad',
          genre: 'romantis',
          title: 'Eternal Sunshine of the Spotless Mind',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/5MwkWH9tYHv3mV9OdYTMR5qreIz.jpg',
          age_rating: '17',
        },
      ],
      entp: [
        {
          mood: 'excited',
          genre: 'aksi',
          title: 'Inception',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg',
          age_rating: '13',
        },
        {
          mood: 'excited',
          genre: 'aksi',
          title: 'The Matrix',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/dXNAPwY7VrqMAo51EKhhCJfaGb5.jpg',
          age_rating: '17',
        },
        {
          mood: 'excited',
          genre: 'fiksi ilmiah',
          title: 'Back to the Future',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/rej4R5DIdlx29I2soNePfInICG3.jpg',
          age_rating: '10',
        },
        {
          mood: 'excited',
          genre: 'fiksi ilmiah',
          title: 'Eternal Sunshine of the Spotless Mind',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/5MwkWH9tYHv3mV9OdYTMR5qreIz.jpg',
          age_rating: '17',
        },
        {
          mood: 'calm',
          genre: 'drama',
          title: 'Fight Club',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg',
          age_rating: '17',
        },
        {
          mood: 'calm',
          genre: 'drama',
          title: 'Catch Me If You Can',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/sdYgEkKCDPWNU6KnoL4qd8xZ4w7.jpgr',
          age_rating: '13',
        },
        {
          mood: 'calm',
          genre: 'misteri',
          title: 'The Usual Suspects',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/rWbsxdwF9qQzpTPCLmDfVnVqTK1.jpg',
          age_rating: '17',
        },
        {
          mood: 'calm',
          genre: 'misteri',
          title: 'Memento',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/nWtySDlffTfwAa0rSfq61o33ZXV.jpg',
          age_rating: '17',
        },
        {
          mood: 'happy',
          genre: 'komedi',
          title: 'Monty Python and the Holy Grail',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/hWx1ANiWEWWyzKPN0us35HCGnhQ.jpg',
          age_rating: '13',
        },
        {
          mood: 'happy',
          genre: 'komedi',
          title: 'The Big Lebowski',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/9mprbw31MGdd66LR0AQKoDMoFRv.jpg',
          age_rating: '17',
        },
        {
          mood: 'happy',
          genre: 'animasi',
          title: 'Rick and Morty',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/gdIrmf2DdY5mgN6ycVP0XlzKzbE.jpg',
          age_rating: '17',
        },
        {
          mood: 'happy',
          genre: 'animasi',
          title: 'South Park',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/xJnbMTrJ2fl1AXAKx34U4BPvOhs.jpg',
          age_rating: '17',
        },
        {
          mood: 'sad',
          genre: 'drama',
          title: 'Good Will Hunting',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/z2FnLKpFi1HPO7BEJxdkv6hpJSU.jpg',
          age_rating: '17',
        },
        {
          mood: 'sad',
          genre: 'drama',
          title: 'Eternal Sunshine of the Spotless Mind',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/5MwkWH9tYHv3mV9OdYTMR5qreIz.jpg',
          age_rating: '17',
        },
        {
          mood: 'sad',
          genre: 'fiksi ilmiah',
          title: 'Her',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/eCOtqtfvn7mxGl6nfmq4b1exJRc.jpg',
          age_rating: '15',
        },
      ],
      infj: [
        {
          mood: 'excited',
          genre: 'drama',
          title: 'The Shawshank Redemption',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg',
          age_rating: '15',
        },
        {
          mood: 'excited',
          genre: 'fantasi',
          title: 'Spirited Away',
          img: 'https://media.themoviedb.org/t/p/w600_and_h900_bestv2/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',
          age_rating: '10',
        },
        {
          mood: 'excited',
          genre: 'fiksi ilmiah',
          title: 'Arrival',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/x2FJsf1ElAgr63Y3PNPtJrcmpoe.jpg',
          age_rating: '13',
        },
        {
          mood: 'calm',
          genre: 'drama',
          title: 'The Green Mile',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/o0lO84GI7qrG6XFvtsPOSV7CTNa.jpg',
          age_rating: '15',
        },
        {
          mood: 'calm',
          genre: 'romantis',
          title: 'Eternal Sunshine of the Spotless Mind',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/5MwkWH9tYHv3mV9OdYTMR5qreIz.jpg',
          age_rating: '17',
        },
        {
          mood: 'calm',
          genre: 'misteri',
          title: 'Zodiac',
          img: 'https://media.themoviedb.org/t/p/w600_and_h900_bestv2/6YmeO4pB7XTh8P8F960O1uA14JO.jpg',
          age_rating: '15',
        },
        {
          mood: 'happy',
          genre: 'komedi',
          title: 'Amélie',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/oTKduWL2tpIKEmkAqF4mFEAWAsv.jpg',
          age_rating: '10',
        },
        {
          mood: 'happy',
          genre: 'drama',
          title: 'The Intouchables',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/1QU7HKgsQbGpzsJbJK4pAVQV9F5.jpg',
          age_rating: '13',
        },
        {
          mood: 'happy',
          genre: 'animasi',
          title: 'Inside Out',
          img: 'https://i.pinimg.com/474x/6d/71/e7/6d71e72ccb7199f965f6b8106267a8e8.jpg',
          age_rating: '10',
        },
        {
          mood: 'sad',
          genre: 'drama',
          title: "Schindler's List",
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg',
          age_rating: '15',
        },
        {
          mood: 'sad',
          genre: 'drama',
          title: 'The Pianist',
          img: 'https://media.themoviedb.org/t/p/w600_and_h900_bestv2/2hFvxCCWrTmCYwfy7yum0GKRi3Y.jpg',
          age_rating: '15',
        },
        {
          mood: 'sad',
          genre: 'romantis',
          title: 'The Notebook',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/rNzQyW4f8B8cQeg7Dgj3n6eT5k9.jpg',
          age_rating: '13',
        },
      ],
      infp: [
        {
          mood: 'excited',
          genre: 'fantasi',
          title: 'Spirited Away',
          img: 'https://media.themoviedb.org/t/p/w600_and_h900_bestv2/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',
          age_rating: '10',
        },
        {
          mood: 'excited',
          genre: 'drama',
          title: 'The Perks of Being a Wallflower',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/aKCvdFFF5n80P2VdS7d8YBwbCjh.jpg',
          age_rating: '13',
        },
        {
          mood: 'excited',
          genre: 'petualangan',
          title: 'Into the Wild',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/jnLnLYP5pGDfri04gxtAqAvkHMw.jpg',
          age_rating: '15',
        },
        {
          mood: 'calm',
          genre: 'drama',
          title: 'Eternal Sunshine of the Spotless Mind',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/5MwkWH9tYHv3mV9OdYTMR5qreIz.jpg',
          age_rating: '17',
        },
        {
          mood: 'calm',
          genre: 'romantis',
          title: 'Before Sunrise',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/kf1Jb1c2JAOqjuzA3H4oDM263uB.jpg',
          age_rating: '15',
        },
        {
          mood: 'calm',
          genre: 'misteri',
          title: 'Zodiac',
          img: 'https://media.themoviedb.org/t/p/w600_and_h900_bestv2/6YmeO4pB7XTh8P8F960O1uA14JO.jpg',
          age_rating: '15',
        },
        {
          mood: 'happy',
          genre: 'komedi',
          title: 'Amélie',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/oTKduWL2tpIKEmkAqF4mFEAWAsv.jpg',
          age_rating: '10',
        },
        {
          mood: 'happy',
          genre: 'komedi romantis',
          title: '500 Days of Summer',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/qXAuQ9hF30sQRsXf40OfRVl0MJZ.jpg',
          age_rating: '13',
        },
        {
          mood: 'happy',
          genre: 'animasi',
          title: 'Inside Out',
          img: 'https://i.pinimg.com/474x/6d/71/e7/6d71e72ccb7199f965f6b8106267a8e8.jpg',
          age_rating: '10',
        },
        {
          mood: 'sad',
          genre: 'drama',
          title: "Schindler's List",
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg',
          age_rating: '15',
        },
        {
          mood: 'sad',
          genre: 'drama',
          title: 'The Pianist',
          img: 'https://media.themoviedb.org/t/p/w600_and_h900_bestv2/2hFvxCCWrTmCYwfy7yum0GKRi3Y.jpg',
          age_rating: '15',
        },
        {
          mood: 'sad',
          genre: 'romantis',
          title: 'The Notebook',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/rNzQyW4f8B8cQeg7Dgj3n6eT5k9.jpg',
          age_rating: '13',
        },
      ],
      enfj: [
        {
          mood: 'excited',
          genre: 'drama',
          title: 'The Shawshank Redemption',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg',
          age_rating: '15',
        },
        {
          mood: 'excited',
          genre: 'petualangan',
          title: 'The Lord of the Rings: The Fellowship of the Ring',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg',
          age_rating: '13',
        },
        {
          mood: 'excited',
          genre: 'komedi',
          title: 'Mamma Mia!',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/zdUA4FNHbXPadzVOJiU0Rgn6cHR.jpg',
          age_rating: '10',
        },
        {
          mood: 'calm',
          genre: 'drama',
          title: 'The Green Mile',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/o0lO84GI7qrG6XFvtsPOSV7CTNa.jpg',
          age_rating: '15',
        },
        {
          mood: 'calm',
          genre: 'romantis',
          title: 'Pride & Prejudice',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/sGjIvtVvTlWnia2zfJfHz81pZ9Q.jpg',
          age_rating: '10',
        },
        {
          mood: 'calm',
          genre: 'misteri',
          title: 'Zodiac',
          img: 'https://media.themoviedb.org/t/p/w600_and_h900_bestv2/6YmeO4pB7XTh8P8F960O1uA14JO.jpg',
          age_rating: '15',
        },
        {
          mood: 'happy',
          genre: 'komedi',
          title: 'Love Actually',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/7QPeVsr9rcFU9Gl90yg0gTOTpVv.jpg',
          age_rating: '15',
        },
        {
          mood: 'happy',
          genre: 'drama',
          title: 'The Intouchables',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/1QU7HKgsQbGpzsJbJK4pAVQV9F5.jpg',
          age_rating: '13',
        },
        {
          mood: 'happy',
          genre: 'animasi',
          title: 'Inside Out',
          img: 'https://i.pinimg.com/474x/6d/71/e7/6d71e72ccb7199f965f6b8106267a8e8.jpg',
          age_rating: '10',
        },
        {
          mood: 'sad',
          genre: 'drama',
          title: "Schindler's List",
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg',
          age_rating: '15',
        },
        {
          mood: 'sad',
          genre: 'drama',
          title: 'The Pianist',
          img: 'https://media.themoviedb.org/t/p/w600_and_h900_bestv2/2hFvxCCWrTmCYwfy7yum0GKRi3Y.jpg',
          age_rating: '15',
        },
        {
          mood: 'sad',
          genre: 'romantis',
          title: 'The Notebook',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/rNzQyW4f8B8cQeg7Dgj3n6eT5k9.jpg',
          age_rating: '13',
        },
      ],
      enfp: [
        {
          mood: 'excited',
          genre: 'fantasi',
          title: 'Spirited Away',
          img: 'https://media.themoviedb.org/t/p/w600_and_h900_bestv2/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',
          age_rating: '10',
        },
        {
          mood: 'excited',
          genre: 'petualangan',
          title: 'The Goonies',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/eBU7gCjTCj9n2LTxvCSIXXOvHkD.jpg',
          age_rating: '10',
        },
        {
          mood: 'excited',
          genre: 'komedi',
          title: "Ferris Bueller's Day Off",
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/w7gDfRXdK8S8GKLvpVepFSLxVZv.jpg',
          age_rating: '13',
        },
        {
          mood: 'calm',
          genre: 'drama',
          title: 'Eternal Sunshine of the Spotless Mind',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/5MwkWH9tYHv3mV9OdYTMR5qreIz.jpg',
          age_rating: '17',
        },
        {
          mood: 'calm',
          genre: 'romantis',
          title: 'Before Sunrise',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/kf1Jb1c2JAOqjuzA3H4oDM263uB.jpg',
          age_rating: '15',
        },
        {
          mood: 'calm',
          genre: 'misteri',
          title: 'Zodiac',
          img: 'https://media.themoviedb.org/t/p/w600_and_h900_bestv2/6YmeO4pB7XTh8P8F960O1uA14JO.jpg',
          age_rating: '15',
        },
        {
          mood: 'happy',
          genre: 'komedi',
          title: 'Amélie',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/oTKduWL2tpIKEmkAqF4mFEAWAsv.jpg',
          age_rating: '10',
        },
        {
          mood: 'happy',
          genre: 'komedi romantis',
          title: '500 Days of Summer',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/qXAuQ9hF30sQRsXf40OfRVl0MJZ.jpg',
          age_rating: '13',
        },
        {
          mood: 'happy',
          genre: 'animasi',
          title: 'Inside Out',
          img: 'https://i.pinimg.com/474x/6d/71/e7/6d71e72ccb7199f965f6b8106267a8e8.jpg',
          age_rating: '10',
        },
        {
          mood: 'sad',
          genre: 'drama',
          title: "Schindler's List",
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg',
          age_rating: '15',
        },
        {
          mood: 'sad',
          genre: 'drama',
          title: 'The Pianist',
          img: 'https://media.themoviedb.org/t/p/w600_and_h900_bestv2/2hFvxCCWrTmCYwfy7yum0GKRi3Y.jpg',
          age_rating: '15',
        },
        {
          mood: 'sad',
          genre: 'romantis',
          title: 'The Notebook',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/rNzQyW4f8B8cQeg7Dgj3n6eT5k9.jpg',
          age_rating: '13',
        },
      ],
      istj: [
        {
          mood: 'excited',
          genre: 'aksi',
          title: 'Mission: Impossible - Fallout',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/AkJQpZp9WoNdj7pLYSj1L0RcMMN.jpg',
          age_rating: '13',
        },
        {
          mood: 'excited',
          genre: 'kriminal',
          title: 'The Departed',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/nT97ifVT2J1yMQmeq20Qblg61T.jpg',
          age_rating: '17',
        },
        {
          mood: 'excited',
          genre: 'fiksi ilmiah',
          title: 'The Martian',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/3ndAx3weG6KDkJIRMCi5vXX6Dyb.jpg',
          age_rating: '13',
        },
        {
          mood: 'calm',
          genre: 'drama',
          title: '12 Angry Men',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg',
          age_rating: '13',
        },
        {
          mood: 'calm',
          genre: 'sejarah',
          title: 'Lincoln',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/qLF0QYnrVDfC1biTCqMBMnZ6AuA.jpg',
          age_rating: '13',
        },
        {
          mood: 'calm',
          genre: 'misteri',
          title: 'Zodiac',
          img: 'https://media.themoviedb.org/t/p/w600_and_h900_bestv2/6YmeO4pB7XTh8P8F960O1uA14JO.jpg',
          age_rating: '15',
        },
        {
          mood: 'happy',
          genre: 'komedi',
          title: 'The Grand Budapest Hotel',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/eWdyYQreja6JGCzqHWXpWHDrrPo.jpg',
          age_rating: '15',
        },
        {
          mood: 'happy',
          genre: 'komedi',
          title: 'Shaun of the Dead',
          img: 'https://media.themoviedb.org/t/p/w600_and_h900_bestv2/dgXPhzNJH8HFTBjXPB177yNx6RI.jpg',
          age_rating: '17',
        },
        {
          mood: 'happy',
          genre: 'animasi',
          title: 'How to Train Your Dragon',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/ygGmAO60t8GyqUo9xYeYxSZAR3b.jpg',
          age_rating: '10',
        },
        {
          mood: 'sad',
          genre: 'drama',
          title: "Schindler's List",
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg',
          age_rating: '15',
        },
        {
          mood: 'sad',
          genre: 'biografi',
          title: 'The Pianist',
          img: 'https://media.themoviedb.org/t/p/w600_and_h900_bestv2/2hFvxCCWrTmCYwfy7yum0GKRi3Y.jpg',
          age_rating: '15',
        },
        {
          mood: 'sad',
          genre: 'drama',
          title: 'Manchester by the Sea',
          img: 'https://media.themoviedb.org/t/p/w600_and_h900_bestv2/o9VXYOuaJxCEKOxbA86xqtwmqYn.jpg',
          age_rating: '17',
        },
      ],
      isfj: [
        {
          mood: 'excited',
          genre: 'drama',
          title: 'The Blind Side',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/bMgq7VBriuBFknXEe9E9pVBYGZq.jpg',
          age_rating: '13',
        },
        {
          mood: 'excited',
          genre: 'komedi',
          title: 'The Proposal',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/aEqtJDj8MvSDQwzggvcOfFTZMw.jpg',
          age_rating: '13',
        },
        {
          mood: 'excited',
          genre: 'animasi',
          title: 'Frozen',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/mmWheq3cFI4tYrZDiATOkCNTqgK.jpg',
          age_rating: '10',
        },
        {
          mood: 'calm',
          genre: 'drama',
          title: 'Forrest Gump',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg',
          age_rating: '13',
        },
        {
          mood: 'calm',
          genre: 'romantis',
          title: 'The Notebook',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/rNzQyW4f8B8cQeg7Dgj3n6eT5k9.jpg',
          age_rating: '13',
        },
        {
          mood: 'calm',
          genre: 'misteri',
          title: 'Knives Out',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/pThyQovXQrw2m0s9x82twj48Jq4.jpg',
          age_rating: '13',
        },
        {
          mood: 'happy',
          genre: 'komedi',
          title: "You've Got Mail",
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/e2uVtH6TpMfUl7WeOM70ezkcjsU.jpg',
          age_rating: '10',
        },
        {
          mood: 'happy',
          genre: 'keluarga',
          title: 'Paddington',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/wpchRGhRhvhtU083PfX2yixXtiw.jpg',
          age_rating: '10',
        },
        {
          mood: 'happy',
          genre: 'animasi',
          title: 'Inside Out',
          img: 'https://i.pinimg.com/474x/6d/71/e7/6d71e72ccb7199f965f6b8106267a8e8.jpg',
          age_rating: '10',
        },
        {
          mood: 'sad',
          genre: 'drama',
          title: 'A Walk to Remember',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/8lUYMvWdHA0Q0k5F76RQCeCBUkA.jpg',
          age_rating: '10',
        },
        {
          mood: 'sad',
          genre: 'drama',
          title: "My Sister's Keeper",
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/atRGqnG7pe0hZP97RWDLrT2hRGZ.jpg',
          age_rating: '13',
        },
        {
          mood: 'sad',
          genre: 'romantis',
          title: 'Me Before You',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/Ia3dzj5LnCj1ZBdlVeJrbKJQxG.jpg',
          age_rating: '13',
        },
      ],
      estj: [
        {
          mood: 'excited',
          genre: 'aksi',
          title: 'Mission: Impossible - Fallout',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/AkJQpZp9WoNdj7pLYSj1L0RcMMN.jpg',
          age_rating: '13',
        },
        {
          mood: 'excited',
          genre: 'kriminal',
          title: 'The Departed',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/nT97ifVT2J1yMQmeq20Qblg61T.jpg',
          age_rating: '17',
        },
        {
          mood: 'excited',
          genre: 'fiksi ilmiah',
          title: 'The Martian',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/3ndAx3weG6KDkJIRMCi5vXX6Dyb.jpg',
          age_rating: '13',
        },
        {
          mood: 'calm',
          genre: 'drama',
          title: '12 Angry Men',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg',
          age_rating: '13',
        },
        {
          mood: 'calm',
          genre: 'sejarah',
          title: 'Lincoln',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/qLF0QYnrVDfC1biTCqMBMnZ6AuA.jpg',
          age_rating: '13',
        },
        {
          mood: 'calm',
          genre: 'misteri',
          title: 'Zodiac',
          img: 'https://media.themoviedb.org/t/p/w600_and_h900_bestv2/6YmeO4pB7XTh8P8F960O1uA14JO.jpg',
          age_rating: '15',
        },
        {
          mood: 'happy',
          genre: 'komedi',
          title: 'The Grand Budapest Hotel',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/eWdyYQreja6JGCzqHWXpWHDrrPo.jpg',
          age_rating: '15',
        },
        {
          mood: 'happy',
          genre: 'komedi',
          title: 'Shaun of the Dead',
          img: 'https://media.themoviedb.org/t/p/w600_and_h900_bestv2/dgXPhzNJH8HFTBjXPB177yNx6RI.jpg',
          age_rating: '17',
        },
        {
          mood: 'happy',
          genre: 'animasi',
          title: 'How to Train Your Dragon',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/ygGmAO60t8GyqUo9xYeYxSZAR3b.jpg',
          age_rating: '10',
        },
        {
          mood: 'sad',
          genre: 'drama',
          title: "Schindler's List",
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg',
          age_rating: '15',
        },
        {
          mood: 'sad',
          genre: 'biografi',
          title: 'The Pianist',
          img: 'https://media.themoviedb.org/t/p/w600_and_h900_bestv2/2hFvxCCWrTmCYwfy7yum0GKRi3Y.jpg',
          age_rating: '15',
        },
        {
          mood: 'sad',
          genre: 'drama',
          title: 'Manchester by the Sea',
          img: 'https://media.themoviedb.org/t/p/w600_and_h900_bestv2/o9VXYOuaJxCEKOxbA86xqtwmqYn.jpg',
          age_rating: '17',
        },
      ],
      esfj: [
        {
          mood: 'excited',
          genre: 'drama',
          title: 'The Blind Side',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/bMgq7VBriuBFknXEe9E9pVBYGZq.jpg',
          age_rating: '13',
        },
        {
          mood: 'excited',
          genre: 'komedi',
          title: 'The Proposal',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/aEqtJDj8MvSDQwzggvcOfFTZMw.jpg',
          age_rating: '13',
        },
        {
          mood: 'excited',
          genre: 'animasi',
          title: 'Frozen',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/mmWheq3cFI4tYrZDiATOkCNTqgK.jpg',
          age_rating: '10',
        },
        {
          mood: 'calm',
          genre: 'drama',
          title: 'Forrest Gump',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg',
          age_rating: '13',
        },
        {
          mood: 'calm',
          genre: 'romantis',
          title: 'The Notebook',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/rNzQyW4f8B8cQeg7Dgj3n6eT5k9.jpg',
          age_rating: '13',
        },
        {
          mood: 'calm',
          genre: 'misteri',
          title: 'Knives Out',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/pThyQovXQrw2m0s9x82twj48Jq4.jpg',
          age_rating: '13',
        },
        {
          mood: 'happy',
          genre: 'komedi',
          title: "You've Got Mail",
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/e2uVtH6TpMfUl7WeOM70ezkcjsU.jpg',
          age_rating: '10',
        },
        {
          mood: 'happy',
          genre: 'keluarga',
          title: 'Paddington',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/wpchRGhRhvhtU083PfX2yixXtiw.jpg',
          age_rating: '10',
        },
        {
          mood: 'happy',
          genre: 'animasi',
          title: 'Inside Out',
          img: 'https://i.pinimg.com/474x/6d/71/e7/6d71e72ccb7199f965f6b8106267a8e8.jpg',
          age_rating: '10',
        },
        {
          mood: 'sad',
          genre: 'drama',
          title: 'A Walk to Remember',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/8lUYMvWdHA0Q0k5F76RQCeCBUkA.jpg',
          age_rating: '10',
        },
        {
          mood: 'sad',
          genre: 'drama',
          title: "My Sister's Keeper",
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/atRGqnG7pe0hZP97RWDLrT2hRGZ.jpg',
          age_rating: '13',
        },
        {
          mood: 'sad',
          genre: 'romantis',
          title: 'Me Before You',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/Ia3dzj5LnCj1ZBdlVeJrbKJQxG.jpg',
          age_rating: '13',
        },
      ],
      istp: [
        {
          mood: 'excited',
          genre: 'aksi',
          title: 'Mad Max: Fury Road',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/8tZYtuWezp8JbcsvHYO0O46tFbo.jpg',
          age_rating: '17',
        },
        {
          mood: 'excited',
          genre: 'kriminal',
          title: 'Drive',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/602vevIURmpDfzbnv5Ubi6wIkQm.jpg',
          age_rating: '17',
        },
        {
          mood: 'excited',
          genre: 'fiksi ilmiah',
          title: 'Blade Runner 2049',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg',
          age_rating: '17',
        },
        {
          mood: 'calm',
          genre: 'drama',
          title: 'There Will Be Blood',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/fa0RDkAlCec0STeMNAhPaF89q6U.jpg',
          age_rating: '17',
        },
        {
          mood: 'calm',
          genre: 'neo-noir',
          title: 'Chinatown',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/kZRSP3FmOcq0xnBulqpUQngJUXY.jpg',
          age_rating: '15',
        },
        {
          mood: 'calm',
          genre: 'misteri',
          title: 'The Big Lebowski',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/9mprbw31MGdd66LR0AQKoDMoFRv.jpg',
          age_rating: '17',
        },
        {
          mood: 'happy',
          genre: 'komedi',
          title: 'Hot Fuzz',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/zPib4ukTSdXvHP9pxGkFCe34f3y.jpg',
          age_rating: '15',
        },
        {
          mood: 'happy',
          genre: 'komedi',
          title: '21 Jump Street',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/9w2y0146P5EjLw63FHGWRRpqQ6v.jpg',
          age_rating: '17',
        },
        {
          mood: 'happy',
          genre: 'animasi',
          title: 'Spider-Man: Into the Spider-Verse',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/iiZZdoQBEYBv6id8su7ImL0oCbD.jpg',
          age_rating: '10',
        },
        {
          mood: 'sad',
          genre: 'drama',
          title: "Schindler's List",
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg',
          age_rating: '15',
        },
        {
          mood: 'sad',
          genre: 'drama',
          title: 'The Pianist',
          img: 'https://media.themoviedb.org/t/p/w600_and_h900_bestv2/2hFvxCCWrTmCYwfy7yum0GKRi3Y.jpg',
          age_rating: '15',
        },
        {
          mood: 'sad',
          genre: 'romantis',
          title: 'Lost in Translation',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/wkSzJs7oMf8MIr9CQVICsvRfwA7.jpg',
          age_rating: '15',
        },
      ],
      isfp: [
        {
          mood: 'excited',
          genre: 'petualangan',
          title: 'Into the Wild',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/jnLnLYP5pGDfri04gxtAqAvkHMw.jpg',
          age_rating: '15',
        },
        {
          mood: 'excited',
          genre: 'drama',
          title: 'The Way',
          img: 'https://media.themoviedb.org/t/p/w300_and_h450_bestv2/bzW0afBIyWZ0bjCje8GPezvETy0.jpg',
          age_rating: '13',
        },
        {
          mood: 'excited',
          genre: 'musik',
          title: 'Sing Street',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/sUWpVlrvzU2SJbnVZqIeKulPKwk.jpg',
          age_rating: '13',
        },
        {
          mood: 'calm',
          genre: 'drama',
          title: 'Eternal Sunshine of the Spotless Mind',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/5MwkWH9tYHv3mV9OdYTMR5qreIz.jpg',
          age_rating: '17',
        },
        {
          mood: 'calm',
          genre: 'romantis',
          title: 'Before Sunrise',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/kf1Jb1c2JAOqjuzA3H4oDM263uB.jpg',
          age_rating: '15',
        },
        {
          mood: 'calm',
          genre: 'misteri',
          title: 'Zodiac',
          img: 'https://media.themoviedb.org/t/p/w600_and_h900_bestv2/6YmeO4pB7XTh8P8F960O1uA14JO.jpg',
          age_rating: '15',
        },
        {
          mood: 'happy',
          genre: 'komedi',
          title: 'Amélie',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/oTKduWL2tpIKEmkAqF4mFEAWAsv.jpg',
          age_rating: '10',
        },
        {
          mood: 'happy',
          genre: 'komedi romantis',
          title: '500 Days of Summer',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/qXAuQ9hF30sQRsXf40OfRVl0MJZ.jpg',
          age_rating: '13',
        },
        {
          mood: 'happy',
          genre: 'animasi',
          title: 'Inside Out',
          img: 'https://i.pinimg.com/474x/6d/71/e7/6d71e72ccb7199f965f6b8106267a8e8.jpg',
          age_rating: '10',
        },
        {
          mood: 'sad',
          genre: 'drama',
          title: "Schindler's List",
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg',
          age_rating: '15',
        },
        {
          mood: 'sad',
          genre: 'drama',
          title: 'The Pianist',
          img: 'https://media.themoviedb.org/t/p/w600_and_h900_bestv2/2hFvxCCWrTmCYwfy7yum0GKRi3Y.jpg',
          age_rating: '15',
        },
        {
          mood: 'sad',
          genre: 'romantis',
          title: 'The Notebook',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/rNzQyW4f8B8cQeg7Dgj3n6eT5k9.jpg',
          age_rating: '13',
        },
      ],
      estp: [
        {
          mood: 'excited',
          genre: 'aksi',
          title: 'Mad Max: Fury Road',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/8tZYtuWezp8JbcsvHYO0O46tFbo.jpg',
          age_rating: '17',
        },
        {
          mood: 'excited',
          genre: 'kriminal',
          title: 'Drive',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/602vevIURmpDfzbnv5Ubi6wIkQm.jpg',
          age_rating: '17',
        },
        {
          mood: 'calm',
          genre: 'drama',
          title: 'The Wolf of Wall Street',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/kW9LmvYHAaS9iA0tHmZVq8hQYoq.jpg',
          age_rating: '17',
        },
        {
          mood: 'calm',
          genre: 'petualangan',
          title: 'The Revenant',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/ji3ecJphATlVgWNY0B0RVXZizdf.jpg',
          age_rating: '17',
        },
        {
          mood: 'calm',
          genre: 'misteri',
          title: 'The Big Lebowski',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/9mprbw31MGdd66LR0AQKoDMoFRv.jpg',
          age_rating: '17',
        },
        {
          mood: 'happy',
          genre: 'komedi',
          title: 'Hot Fuzz',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/zPib4ukTSdXvHP9pxGkFCe34f3y.jpg',
          age_rating: '15',
        },
        {
          mood: 'happy',
          genre: 'komedi',
          title: '21 Jump Street',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/9w2y0146P5EjLw63FHGWRRpqQ6v.jpg',
          age_rating: '17',
        },
        {
          mood: 'happy',
          genre: 'animasi',
          title: 'Spider-Man: Into the Spider-Verse',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/iiZZdoQBEYBv6id8su7ImL0oCbD.jpg',
          age_rating: '10',
        },
        {
          mood: 'sad',
          genre: 'drama',
          title: "Schindler's List",
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg',
          age_rating: '15',
        },
        {
          mood: 'sad',
          genre: 'drama',
          title: 'The Pianist',
          img: 'https://media.themoviedb.org/t/p/w600_and_h900_bestv2/2hFvxCCWrTmCYwfy7yum0GKRi3Y.jpg',
          age_rating: '15',
        },
        {
          mood: 'sad',
          genre: 'romantis',
          title: 'Lost in Translation',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/wkSzJs7oMf8MIr9CQVICsvRfwA7.jpg',
          age_rating: '15',
        },
      ],
      esfp: [
        {
          mood: 'excited',
          genre: 'komedi',
          title: '21 Jump Street',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/9w2y0146P5EjLw63FHGWRRpqQ6v.jpg',
          age_rating: '17',
        },
        {
          mood: 'excited',
          genre: 'petualangan',
          title: 'The Goonies',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/eBU7gCjTCj9n2LTxvCSIXXOvHkD.jpg',
          age_rating: '10',
        },
        {
          mood: 'excited',
          genre: 'musik',
          title: 'Pitch Perfect',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/cUjjK6tTrugybsBbIQlV6VTd0aK.jpg',
          age_rating: '13',
        },
        {
          mood: 'calm',
          genre: 'drama',
          title: 'The Wolf of Wall Street',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/kW9LmvYHAaS9iA0tHmZVq8hQYoq.jpg',
          age_rating: '17',
        },
        {
          mood: 'calm',
          genre: 'komedi romantis',
          title: 'Crazy, Stupid, Love.',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/p4RafgAPk558muOjnBMHhMArjS2.jpg',
          age_rating: '13',
        },
        {
          mood: 'calm',
          genre: 'misteri',
          title: 'Knives Out',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/pThyQovXQrw2m0s9x82twj48Jq4.jpg',
          age_rating: '13',
        },
        {
          mood: 'happy',
          genre: 'komedi',
          title: 'Mean Girls',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/alKvY5LuVcXraRBfi5UtVV8Ii6Y.jpg',
          age_rating: '13',
        },
        {
          mood: 'happy',
          genre: 'komedi romantis',
          title: 'Set It Up',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/7omfwqiiMld9EnUps3Uk9YZLy6g.jpg',
          age_rating: '13',
        },
        {
          mood: 'happy',
          genre: 'animasi',
          title: 'Tangled',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/ym7Kst6a4uodryxqbGOxmewF235.jpg',
          age_rating: '10',
        },
        {
          mood: 'sad',
          genre: 'drama',
          title: 'A Walk to Remember',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/8lUYMvWdHA0Q0k5F76RQCeCBUkA.jpg',
          age_rating: '10',
        },
        {
          mood: 'sad',
          genre: 'drama',
          title: 'The Perks of Being a Wallflower',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/aKCvdFFF5n80P2VdS7d8YBwbCjh.jpg',
          age_rating: '13',
        },
        {
          mood: 'sad',
          genre: 'romantis',
          title: 'Me Before You',
          img: 'https://media.themoviedb.org/t/p/w188_and_h282_bestv2/Ia3dzj5LnCj1ZBdlVeJrbKJQxG.jpg',
          age_rating: '13',
        },
      ],
    };
    // AKHIR DARI BANK FILM

    // Filter film sesuai input
    const rekomendasi = filmData[mbti].filter(
      (film) =>
        film.mood === mood &&
        film.genre === genre &&
        parseInt(film.age_rating) === parseInt(umur)
    );

    if (rekomendasi.length === 0) {
      filmList.innerHTML =
        '<p>Tidak ada film yang cocok dengan kriteria Anda.</p>';
    } else {
      rekomendasi.forEach((film) => {
        const filmCard = document.createElement('div');
        filmCard.classList.add('film-card');
        filmCard.innerHTML = `
                  <img src="${film.img}" alt="${film.title}">
                  <h2>${film.title}</h2>
                  <p>Genre: ${film.genre}</p>
                  <p>Rating Usia: ${film.age_rating}</p>
              `;
        filmList.appendChild(filmCard);
      });
    }
  });

  // Data film contoh (nanti bisa ditambahkan lebih banyak di script.js)

  //
});
